core_dashboard:
    resource: "@CoreDashboardBundle/Resources/config/routing.yml"
    prefix:   /

core_users:
    resource: "@CoreUsersBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
