core_dashboard:
    resource: "@CoreDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

core_users:
    resource: "@CoreUsersBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

crone_job:
    resource: "@CoreDashboardBundle/Resources/config/crone.yml"
    prefix:   /crone