# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_EXTERNAL:    ROLE_EXTERNAL
        ROLE_INTERNAL:    ROLE_INTERNAL
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me:  true
                csrf_token_generator: security.csrf.token_manager
                login_path: /
                default_target_path: /home
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path:       fos_user_security_logout
                target:     /
            anonymous:    true
            access_denied_url: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/, roles: [ROLE_EXTERNAL, ROLE_INTERNAL,ROLE_ADMIN ] }
        - { path: ^/dashboard/home/admin, role: ROLE_ADMIN }
        - { path: ^/dashboard/home/external, role: ROLE_EXTERNAL }
        - { path: ^/dashboard/home/internals ,role: ROLE_INTERNAL }
        - { path: ^/group, role: ROLE_ADMIN }
        - { path: ^/crone, role: IS_AUTHENTICATED_ANONYMOUSLY }